#################################################
### Do not edit this file directly            ###
### This file is automatically generated      ###
### Source: <ROOT>/assets                     ###
#################################################
# install packages
apt update
apt install -y tree